# Generated by Django 5.1.1 on 2025-01-02 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='user',
            name='trades_count',
            field=models.IntegerField(default=0),
        ),
    ]
