# Generated by Django 5.1.1 on 2024-12-31 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0008_alter_tradeoffer_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradeoffer',
            old_name='service',
            new_name='offerType',
        ),
    ]
