# Generated by Django 5.1.1 on 2025-01-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0009_rename_service_tradeoffer_offertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='image',
            field=models.ImageField(blank=True, upload_to='comic_images'),
        ),
        migrations.AlterField(
            model_name='tradeoffer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trade_images'),
        ),
    ]
