# Generated by Django 5.1.1 on 2025-01-05 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0010_alter_comic_image_alter_tradeoffer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeoffer',
            name='date',
            field=models.DateField(),
        ),
    ]
