# Generated by Django 5.1.1 on 2025-01-05 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0011_alter_tradeoffer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeoffer',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
