# Generated by Django 5.1.1 on 2025-01-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0012_alter_tradeoffer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='image',
            field=models.ImageField(upload_to='comic_images'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
